# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a15c915afc7fa0063b465837babb8942e7df9c3ceaabb66eaaa526f8b1aa4bd1577cdaa1133e5bb3446f036cff0c8c86aa218ed16a0a651f4bb2e98eb446ef53

test:
  secret_key_base: 6f177ed0c22f0b53c87ae210b7c1eccb4691c5983eaa76e9c0330c1e4c441397a2e1bdd254e7726a60719b3a58d60b1d401cab2d0c1ecabe83bd65dd6247c1fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
